# Generated by Django 3.0.5 on 2021-11-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('instrument_purchase', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('', 'Choose...'), ('MG', 'Minas Gerais'), ('SP', 'Sao Gerais'), ('RJ', 'Rio de Janerio')], max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
