# Generated by Django 3.0.5 on 2021-11-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
