# Generated by Django 3.0.5 on 2021-11-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211118_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address_line1',
            new_name='address',
        ),
    ]
